CREATE DATABASE QuanLyQuanCafe
GO

USE QuanLyQuanCafe
GO

CREATE TABLE Account
(
	userName NVARCHAR(100) PRIMARY KEY,	
	displayName NVARCHAR(100) NOT NULL DEFAULT N'CafeManager',
	passWord NVARCHAR(1000) NOT NULL DEFAULT 0,
	Type INT NOT NULL  DEFAULT 0 -- 1: quản lí && 0: nhân viên
)
GO

CREATE TABLE Ban
(
	id INT IDENTITY PRIMARY KEY,
	status NVARCHAR(100) NOT NULL DEFAULT N'Trống'	-- Trống || Có người
)
GO

CREATE TABLE LoaiThucAn
(
	id INT IDENTITY PRIMARY KEY,
	name NVARCHAR(100) NOT NULL DEFAULT N'Chưa đặt tên'
)
GO

CREATE TABLE ThucAn
(
	id INT IDENTITY PRIMARY KEY,
	name NVARCHAR(100) NOT NULL DEFAULT N'Chưa đặt tên',
	idThucAn INT NOT NULL,
	gia FLOAT NOT NULL DEFAULT 0
	FOREIGN KEY (idThucAn) REFERENCES dbo.LoaiThucAn(id) ON DELETE CASCADE ON UPDATE CASCADE
)
GO

CREATE TABLE HoaDon
(
	id INT IDENTITY PRIMARY KEY,
	ngayTao DATE NOT NULL DEFAULT GETDATE(),
	idBan INT NOT NULL,
	status INT NOT NULL DEFAULT 0 -- 1: đã thanh toán && 0: chưa thanh toán
	
	FOREIGN KEY (idBan) REFERENCES dbo.Ban(id) ON DELETE CASCADE ON UPDATE CASCADE
)
GO

CREATE TABLE CTHoaDon
(
	id INT IDENTITY PRIMARY KEY,
	idHoaDon INT NOT NULL,
	idThucAn INT NOT NULL,
	tong INT NOT NULL DEFAULT 0
	
	FOREIGN KEY (idHoaDon) REFERENCES dbo.HoaDon(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (idThucAn) REFERENCES dbo.ThucAn(id) ON DELETE CASCADE ON UPDATE CASCADE
)
GO